

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops7.fullname" . }}-configmap
data:
  FLASK_ENV: {{ .Values.configmap.FLASK_ENV }}
  MY_HOST: {{ .Values.configmap.MY_HOST| default (include "devops7.fullname" . ) }}-mysql-clusterip
  MY_DB: {{ .Values.configmap.MY_DB }}
  db.sh: |   
    {{ .Values.configmap.db_script | nindent 4}}

 




