
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops7.fullname" . }}-flask-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingress_controller }}
spec:
  rules:
  - host: {{ .Values.ingress.ingress_host }}
    http:
      paths:
      - path: {{ .Values.ingress.path}}
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops7.fullname" . }}-flask-service
            port:
              number: {{ .Values.ingress.ingress_port }}
{{- end }}
