
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops7.fullname" . }}-secret1
type: Opaque
data:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops7.fullname" . }}-secret2
type: Opaque
data:
  root_password: {{ .Values.secrets.rootpassword }}
