
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  username: Zmxhc2t1c2Vy
  password: cGF0b2RlZ29tYQ==


---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: cm9vdDEyMzQ=